code --install-extension abusaidm.html-snippets
code --install-extension Angular.ng-template
code --install-extension christian-kohler.path-intellisense
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension humao.rest-client
code --install-extension jebbs.plantuml
code --install-extension johnpapa.Angular2
code --install-extension mohsen1.prettify-json
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension robertohuertasm.vscode-icons
code --install-extension vscodevim.vim
code --install-extension wmaurer.change-case
code --install-extension Zignd.html-css-class-completion
code --install-extension ziyasal.vscode-open-in-github
